### ISSUE TITLE
Installation fails due to distutils deprecation

### ISSUE THREAD

**Issue by FedericoThiella** [kcroker/dpsprep#11]
`disutils` seems deprecated in latest python releases (3.9 and above. The installation fails because of a Deprecation Warning

**Comment by v--** [comment]
The project doesn't use distutils directly. Perhaps you were seeing an error with the installation of `python-djvulibre`, which has been fixed in https://github.com/kcroker/dpsprep/pull/10.

Does the project install with the newly merged pull requests?

**Comment by v--** [comment]
@FedericoThiella have you had the opportunity to try installing dpsprep since my latest answer?

**Comment by v--** [comment]
@FedericoThiella I'm going to close the issue. You should be able to reopen it if needed.
