### ISSUE TITLE
ImportError: No module named sexpdata

### ISSUE THREAD

**Issue by agitato816** [kcroker/dpsprep#2]
It won't work. I tried it on Ubuntu 14.04 x64

=====

$ ./dpsprep book.djvu 
Traceback (most recent call last):
  File "./dpsprep", line 6, in <module>
    import sexpdata
ImportError: No module named sexpdata

=====

How to convert DJVU to PDF properly with keeping outline and searchable text?

Thanks,
jonghyun

**Comment by kcroker** [comment]
Please see NOTE 1.5 on the README.md page :)

"NOTE 1.5: you will need the sexpdata Python module. It is provided in Ubuntu under the package python-pyparsing"

You must:
sudo apt-get install python-pyparsing
