### ISSUE TITLE
Make dpsprep work with python 3

### ISSUE THREAD

**Issue by opensource-philosophy** [kcroker/dpsprep#7]
Is there any way to make the script compatible with the newest python version without rewriting it? That'd be great!

**Comment by kcroker** [comment]
If I get a free weekend, I can probably re-write it in Python 3 and
possibly reduce some of the external dependencies.  The problem is that
free weekend 😅

**Comment by opensource-philosophy** [comment]
I understand! I really appreciate your efforts and love using `dpsprep`. If it's any incentive to you, I'd like to make a donation of 50$ for re-writing the script - no strings attached, no dead line or anything. I know it's not much, but that's all I can offer at the moment. Great opensource-projects such as yours should be supported!

**Comment by v--** [comment]
@opensource-philosophy dpsprep works perfectly fine with Python 3. One of the dependencies - ocrodjvu - has recently been abandoned amdst it's Python 3 port. The best you can do is use dpsprep with the python3 branch of https://github.com/rmast/ocrodjvu .
